name: "Install Skopeo"
description: "Install Skopeo with version input support."
author: "Jetsung Chan"
branding:
  icon: "zap"
  color: "blue"
inputs:
  version:
    description: "Skopeo version (e.g. 1.12.0, latest). Leave empty for latest stable."
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Setup Go environment
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    - name: Check go version
      run: go version
    - name: "Install Dependencies"
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgpgme-dev \
          libassuan-dev \
          libdevmapper-dev \
          pkg-config      
    - name: Get Skopeo version
      run: |
        if [ -z "${{ inputs.version }}" ]; then
          echo "Version is empty, using latest stable"
          export SKOPEO_VERSION=$(curl -s https://api.github.com/repos/containers/skopeo/releases/latest | jq -r '.tag_name' | sed 's/v//')
        elif [[ "${{ inputs.version }}" == "dev" || "${{ inputs.version }}" == "master" ]]; then
          echo "Version is dev, using master"
          export SKOPEO_VERSION=""
        else
          echo "Version is ${{ inputs.version }}, using it"
          export SKOPEO_VERSION=${{ inputs.version }}
        fi
        echo "SKOPEO_VERSION=$SKOPEO_VERSION" >> $GITHUB_ENV
    - name: Get Skopeo source code
      run: |
        git clone https://github.com/containers/skopeo.git $GOPATH/src/github.com/containers/skopeo
        cd $GOPATH/src/github.com/containers/skopeo
        if [ -n "${{ env.SKOPEO_VERSION }}" ]; then
          echo "Checking out v${{ env.SKOPEO_VERSION }}"
          git checkout v${{ env.SKOPEO_VERSION }}
        fi
        make bin/skopeo
        sudo cp bin/skopeo /usr/local/bin/skopeo
    - name: Check Skopeo version
      run: |
        skopeo --version
